Repository Kr-Shanu/DBMS_Learning_Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#2 Er model introduction issue #1
  ERmodel/erModel.md
Labels: question

#4 ER Model readme fixed
  ERmodel/README.md
Labels: hacktoberfest

#11 Er model
  Relational/Introduction/README.MD
  Relational/README.MD
Labels: hacktoberfest, hacktoberfest-accepted

#12 codd readme updated
  ERmodel/README.md
  Relational/CODD/README.MD
  Relational/Introduction/README.MD
  Relational/README.MD
Labels: hacktoberfest

#13 Added the file
  Anomalies/readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#14 Added all the topics as per issue
  ERmodel/ER Model: Generalization, Specialization and Aggregation/README.md
  ERmodel/Enhanced ER Model/README.md
  ERmodel/Impedance Mismatch/README.md
  ERmodel/Minimization of ER Diagrams/README.md
  ERmodel/Recursive Relationships/README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#19 added number of possible superkeys topic
  Relational/Number of possible Superkeys/readme.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#20 added schema integration readme
  Relational/Schema Integration/readme.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#21 added strategies for schema
  Relational/Strategies for Schema/readme.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#22 Added intro to DBMS
  Intro to dbms/readme.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#23 Added database object
  Intro to dbms/Database object/readme.md
Labels: documentation, good first issue, hacktoberfest

#25 Added Use of DBMS
  Intro to dbms/Use of DBMS/readme.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#24 Added Need of DBMS
  Intro to dbms/Need of dbms/readme.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#26 Added the Mapping from ER Model to Relational Model
  Intro to dbms/Data Abstraction and Data Independence/README.MD
  Relational/Mapping ER Model to Relational Model/README.MD
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#34 185_DepartmentTopThreeSalaries.sql
  Leetcode_DBMS_Questions/185_DepartmentTopThreeSalaries.sql
Labels: hacktoberfest, hacktoberfest-accepted

#38 197_RisingTemperature.sql
  Leetcode_DBMS_Questions/197_RisingTemperature.sql
Labels: hacktoberfest, hacktoberfest-accepted

#37 184_DepartmentHighestSalary.sql
  Leetcode_DBMS_Questions/184_DepartmentHighestSalary.sql
Labels: hacktoberfest, hacktoberfest-accepted

#36 183_CustomersWhoNeverOrder.sql
  Leetcode_DBMS_Questions/183_CustomersWhoNeverOrder.sql
Labels: hacktoberfest, hacktoberfest-accepted

#35 182_DuplicateEmails.sql
  Leetcode_DBMS_Questions/182_DuplicateEmails.sql
Labels: hacktoberfest, hacktoberfest-accepted
